export default {
  GET_REPOS_FROM_GITHUB: "GET_REPOS_FROM_GITHUB",
  GET_REPOS_FROM_GITHUB_SUCCESS: "GET_REPOS_FROM_GITHUB_SUCCESS",
  GET_REPOS_FROM_GITHUB_ERROR: "GET_REPOS_FROM_GITHUB_ERROR",
  SET_SEARCH_CRITERIA: "SET_SEARCH_CRITERIA",
  LOAD_MORE_REPOS_FROM_GITHUB: "LOAD_MORE_REPOS_FROM_GITHUB",
  LOAD_MORE_REPOS_FROM_GITHUB_SUCCESS: "LOAD_MORE_REPOS_FROM_GITHUB_SUCCESS"
};
