export default {
  GET_REPOS_FROM_GITHUB: "GET_REPOS_FROM_GITHUB",
  GET_REPOS_FROM_GITHUB_SUCCESS: "GET_REPOS_FROM_GITHUB_SUCCESS",
  GET_REPOS_FROM_GITHUB_ERROR: "GET_REPOS_FROM_GITHUB_ERROR",
  SET_SEARCH_QUERY_STRING: "SET_SEARCH_QUERY_STRING"
};
